name: 'Build and upload to S3 Bucket'

on: [push]
#on:
#  push:
#    branches:
#      - master

jobs:
  Build_and_Upload:
    permissions:
      actions: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package shade:shade -Ph2
      - name: 'Generate Tag Version'
        id: generate_tag_version
        run: |
          TAG=0.0.2-$(date +%Y%m%d)-$(date +%H%M%S)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Tag Version: $TAG" >> $GITHUB_STEP_SUMMARY

      - name: 'Create package name'
        id: 'create_package'
        run: |
          mv target/app-0.0.1-SNAPSHOT.jar target/${{ steps.generate_tag_version.outputs.tag }}.jar
          PACKAGE_NAME="target/${{ steps.generate_tag_version.outputs.tag }}.jar"
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
#          zip -r $PACKAGE_NAME .

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_BUCKET_USER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_BUCKET_USER_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_S3_BUCKET_REGION }}

      - name: 'Upload to S3 Bucket'
        run: |
          ls target
          aws s3 cp ${{ steps.create_package.outputs.package_name }} s3://${{ secrets.AWS_S3_BUCKET_NAME }}
